const layouts = [
  {
    scale: 1,
    bodySize: 10.5,
    lineHeight: 1.45,
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 40,
    sectionGap: 12,
    entryGap: 9.8,
    photoWidth: 54,
    photoHeight: 72,
    photoReserve: 82,
    headerMinHeight: 74,
  },
  {
    scale: 0.96,
    bodySize: 10,
    lineHeight: 1.4,
    paddingTop: 34,
    paddingBottom: 34,
    paddingHorizontal: 34,
    sectionGap: 10,
    entryGap: 8.2,
    photoWidth: 50,
    photoHeight: 67,
    photoReserve: 75,
    headerMinHeight: 69,
  },
  {
    scale: 0.92,
    bodySize: 9.4,
    lineHeight: 1.34,
    paddingTop: 29,
    paddingBottom: 29,
    paddingHorizontal: 29,
    sectionGap: 8,
    entryGap: 6.6,
    photoWidth: 45,
    photoHeight: 60,
    photoReserve: 68,
    headerMinHeight: 62,
  },
  {
    scale: 0.82,
    bodySize: 8.1,
    lineHeight: 1.2,
    paddingTop: 17,
    paddingBottom: 17,
    paddingHorizontal: 23,
    sectionGap: 4.5,
    entryGap: 3.5,
    photoWidth: 36,
    photoHeight: 48,
    photoReserve: 54,
    headerMinHeight: 50,
  },
];

export function getResumeLayout(level = 0) {
  return layouts[level] || layouts[3];
}
